import rock from '../images/Boundary.png';
import space from '../images/space.jpg';
import finish from '../images/finishline.gif'
import clock from '../images/clock.png'
import wormhole from '../images/wormhole.gif'
import Player from '../components/Player.jsx';

export const levels = [

        [rock,rock,rock,rock,rock,
        Player,space,space,space,space,
        rock,rock,rock,rock,space,
        space,space,wormhole,rock,space,
        space,rock,space,rock,space,
        space,rock,rock,rock,space,
        space,rock,space,space,space,
        space,rock,space,space,space,
        space,space,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,space,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,rock,rock,
        space,rock,space,space,space,
        space,rock,rock,rock,space,
        space,rock,space,rock,space,
        space,space,space,space,space,
        space,rock,space,rock,space,
        space,rock,rock,rock,space,
        space,space,space,space,space,
        space,rock,space,rock,finish],

        [rock,rock,rock,rock,rock,
        Player,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,space,space,rock,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,space,space,
        space,rock,rock,space,space,
        space,rock,rock,rock,space,
        space,space,rock,rock,space,
        rock,space,rock,wormhole,space,
        rock,space,rock,rock,space,
        rock,space,wormhole,rock,space,
        space,space,rock,rock,space,
        space,space,space,rock,space,
        rock,rock,space,rock,space,
        rock,rock,clock,rock,space,
        rock,rock,rock,rock,space,
        space,space,space,space,space,
        space,rock,rock,rock,space,
        space,rock,rock,space,space,
        clock,rock,space,space,space,
        rock,space,space,rock,space,
        space,space,rock,clock,space,
        finish,rock,rock,rock,rock],

        [space,space,space,space,Player,
        space,rock,rock,rock,rock,
        space,space,space,space,wormhole,
        rock,space,space,rock,rock,
        rock,rock,space,space,rock,
        space,clock,rock,space,rock,
        space,rock,space,space,space,
        space,rock,space,rock,space,
        space,space,rock,space,space,
        space,space,rock,space,space,
        space,rock,rock,space,rock,
        space,space,space,space,rock,
        rock,rock,space,rock,rock,
        rock,space,space,space,space,
        space,space,rock,rock,space,
        space,rock,rock,space,space,
        wormhole,rock,rock,space,rock,
        rock,rock,wormhole,space,space,
        clock,space,rock,rock,space,
        rock,space,rock,space,space,
        rock,space,space,space,space,
        rock,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,rock,space,space,
        finish,rock,rock,clock,rock],

        [rock,rock,rock,rock,rock,
        Player,space,rock,clock,rock,
        space,rock,rock,space,space,
        space,space,space,rock,space,
        space,rock,space,rock,space,
        space,space,rock,space,space,
        space,space,rock,space,space,
        rock,space,rock,space,space,
        space,space,space,space,rock,
        rock,space,rock,space,rock,
        space,space,space,space,rock,
        space,space,space,rock,rock,
        space,rock,space,space,space,
        rock,wormhole,rock,rock,space,
        rock,space,space,rock,space,
        space,rock,space,space,space,
        space,clock,rock,space,space,
        space,rock,space,rock,space,
        space,space,space,rock,space,
        space,rock,rock,rock,space,
        space,space,space,rock,space,
        rock,rock,space,rock,space,
        space,space,space,space,space,
        space,rock,rock,rock,rock,
        space,space,space,space,finish],

        [space,space,Player,space,space,
        rock,space,rock,rock,space,
        space,space,rock,rock,space,
        rock,rock,space,space,space,
        space,rock,space,rock,space,
        space,rock,space,wormhole,rock,
        space,rock,space,space,rock,
        space,rock,rock,space,space,
        space,rock,rock,rock,space,
        space,rock,rock,space,space,
        space,rock,wormhole,rock,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        space,rock,space,space,space,
        space,rock,rock,rock,space,
        space,space,space,space,space,
        space,rock,rock,rock,rock,
        space,space,space,space,space,
        space,rock,space,rock,space,
        space,rock,space,rock,space,
        rock,rock,clock,rock,space,
        clock,space,rock,space,space,
        rock,space,space,space,rock,
        rock,rock,space,rock,rock,
        finish,space,space,clock]]
